### ISSUE TITLE
Meshalyzer does not compile: Frame.cc: ‘glDeleteRenderbuffersEXT’ was not declared in this scope

### ISSUE THREAD

**Issue by Batazai** [cardiosolv/meshalyzer#1]
Hello,
Following the instructions on https://carpentry.medunigraz.at/carputils/getting-started/visualization-tools.html#meshalyzer to install meshalyzer I get the following error:
```
baltasar@computer: make
[...]
Frame.cc: In member function ‘void Frame::delete_objs()’:
Frame.cc:33:3: error: ‘glDeleteRenderbuffersEXT’ was not declared in this scope
   glDeleteRenderbuffersEXT(1, &_color_rb);
   ^~~~~~~~~~~~~~~~~~~~~~~~
Frame.cc:33:3: note: suggested alternative: ‘glDeleteTextures’
   glDeleteRenderbuffersEXT(1, &_color_rb);

[... and similar for glDeleteRenderbuffersEXT,  glGenFramebuffersEXT, 
glBindFramebufferEXT, glGenRenderbuffersEXT, glBindRenderbufferEXT, 
glRenderbufferStorageEXT, glFramebufferRenderbufferEXT,
glCheckFramebufferStatusEXT, glBindFramebufferEXT ...]

make: *** [<builtin>: Frame.o] Error 1
```

The log from the make command is  [appended](https://github.com/cardiosolv/meshalyzer/files/2982727/meshalyzer_not_install_log.txt). Because of the colour code inside it can be best displayed by ```cat meshalyzer_not_install_log.txt```.

If there is anything else you need, I'll be happy to provide the information.
Thank you in advance

Baltasar

**Comment by vigmond** [comment]
Hi Do you have a recent version of GL? I have heard that GLee no longer works and I need to switch to GLEW. My colleague downgraded the version of his library. 

I am planning to upgrade to GLEW when I get some free time.

Cheers
Ed

————
Edward Vigmond, Ph.D.
Chercheur, Institut de Rythmologie et de modélisation cardiaque (LIRYC) Université Bordeaux
 IHU LIRYC 
Hôpital Xavier Arnozan
Avenue du Haut-Lévêque 
33604 Cedex Pessac France
+33(0)535381918

**Comment by Batazai** [comment]
Hi,
Thanks for the fast response!

I have GL version 4.6.0.. It is the newest but from 2017. Can you recommend another version?
I found mine using visualinfo of the  ```glew-utils``` package using ```visualinfo | grep "OpenGL version"```.

I tried to changed it to glew myself but I didn't manage to do so. If you could take a look into it it would be great.
Thanks

Baltasar

**Comment by ajprassl** [comment]
I had the exact same issue on a Fedora 29 machine.

According to glxinfo the GL version is the same as yours - see below:
OpenGL version string: 4.6.0 NVIDIA 418.43
OpenGL shading language version string: 4.60 NVIDIA

To fix the issue, I had to downgrade **mesa-libGL-18.3.4-1** to **mesa-libGL-18.2.2-1**. A couple of other packages were following to preserve consistency.

Cheers,
Toni
